CC = g++
C_FLAGS = -std=c++11 -Wall -Wextra -g
TAR_NAME = ex2.tar
TAR_FILES = README Makefile
VALGRIND_FLAGS = --leak-check=full --show-possibly-lost=yes --show-reachable=yes --undef-value-errors=yes

MIR: MIR.o
	echo Something

MIR.o:
	echo Something

clean:
	rm -fv *.o *.exe*

.PHONY: all clean